// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class db_errors
    {
        public string USER_SNAME { get; set; }
        public string ERROR_NUMBER { get; set; }
        public string ERROR_STATE { get; set; }
        public string ERROR_SEVERITy { get; set; }
        public string ERROR_LINE { get; set; }
        public string ERROR_PROCEDURE { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public DateTime? RUN_DATETIME { get; set; }
    }
}