// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class DIM_BUSINESSORG_test
    {
        public string ENT_COUNTRY_GROUP_CODE { get; set; }
        public string ENT_COUNTRY_GROUP_LONG_NAME { get; set; }
        public string ENT_COUNTRY_GROUP_SHORT_NAME { get; set; }
        public string ENT_COUNTRY_CODE { get; set; }
        public string ENT_COUNTRY_LONG_NAME { get; set; }
        public string ENT_COUNTRY_SHORT_NAME { get; set; }
        public string ENT_MASTER_GROUP_CODE { get; set; }
        public string ENT_MASTER_GROUP_LONG_NAME { get; set; }
        public string ENT_MASTER_GROUP_SHORT_NAME { get; set; }
        public string ENT_GROUP_CODE { get; set; }
        public string ENT_GROUP_LONG_NAME { get; set; }
        public string ENT_GROUP_SHORT_NAME { get; set; }
        public string ENT_ENTITY_CODE { get; set; }
        public string ENT_ENTITY_LONG_NAME { get; set; }
        public string ENT_ENTITY_SHORT_NAME { get; set; }
        public string ENT_SUB_GROUP_CODE { get; set; }
        public string ENT_SUB_GROUP_LONG_NAME { get; set; }
        public string ENT_SUB_GROUP_SHORT_NAME { get; set; }
        public string ENT_SITE_CODE { get; set; }
        public string ENT_SITE_LONG_NAME { get; set; }
        public string SRC_ENT_SITE_CODE { get; set; }
        public string SRC_ENT_SITE_DESC { get; set; }
        public DateTime? DATE_FROM { get; set; }
        public DateTime? DATE_TO { get; set; }
    }
}