// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class DIM_OUTLETSEGMENTATION
    {
        public string OSG_OUTLET_SEGMENT_GROUP_CODE { get; set; }
        public string OSG_OUTLET_SEGMENT_GROUP_LONG_NAME { get; set; }
        public string OSG_OUTLET_SEGMENT_GROUP_SHORT_NAME { get; set; }
        public string OSG_OUTLET_SEGMENT_CODE { get; set; }
        public string OSG_OUTLET_SEGMENT_LONG_NAME { get; set; }
        public string OSG_OUTLET_SEGMENT_SHORT_NAME { get; set; }
        public string OSG_OUTLET_SUB_SEGMENT_CODE { get; set; }
        public string OSG_OUTLET_SUB_SEGMENT_LONG_NAME { get; set; }
        public string OSG_OUTLET_SUB_SEGMENT_SHORT_NAME { get; set; }
        public string OSG_OUTLET_SEGMENT_TYPE_CODE { get; set; }
        public string OSG_OUTLET_SEGMENT_TYPE_LONG_NAME { get; set; }
        public string OSG_OUTLET_SEGMENT_TYPE_SHORT_NAME { get; set; }
        public DateTime? DATE_FROM { get; set; }
        public DateTime? DATE_TO { get; set; }
    }
}