// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class DIM_LOOKUP_test
    {
        public int LOOKUPID { get; set; }
        public int? ENTITY_TYPE_ID { get; set; }
        public string LOOKUP_TYPE { get; set; }
        public string LOOKUP_CODE { get; set; }
        public string LOOK_DESC { get; set; }
    }
}