// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class DIM_PRODUCT
    {
        public string BPP_PRODUCT_CODE { get; set; }
        public string BPP_PRODUCT_LONG_NAME { get; set; }
        public string BPP_PRODUCT_SHORT_NAME { get; set; }
        public string PRODUCT_ORIGIN { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string BPP_BEVERAGE_SUB_TYPE_CODE { get; set; }
        public string BPP_BEVERAGE_SUB_TYPE_LONG_NAME { get; set; }
        public string BPP_BEVERAGE_SUB_TYPE_SHORT_NAME { get; set; }
        public string BPP_BEVERAGE_TYPE_CODE { get; set; }
        public string BPP_BEVERAGE_TYPE_LONG_NAME { get; set; }
        public string BPP_BEVERAGE_TYPE_SHORT_NAME { get; set; }
        public string BPP_BEVERAGE_SUB_GROUP_CODE { get; set; }
        public string BPP_BEVERAGE_SUB_GROUP_LONG_NAME { get; set; }
        public string BPP_BEVERAGE_SUB_GROUP_SHORT_NAME { get; set; }
        public string BPP_BEVERAGE_GROUP_CODE { get; set; }
        public string BPP_BEVERAGE_GROUP_LONG_NAME { get; set; }
        public string BPP_BEVERAGE_GROUP_SHORT_NAME { get; set; }
        public string BPP_INDUSTRY_TYPE_CODE { get; set; }
        public string BPP_INDUSTRY_TYPE_LONG_NAME { get; set; }
        public string BPP_INDUSTRY_TYPE_SHORT_NAME { get; set; }
        public string BPP_CATEGORY_SEGMENT_CODE { get; set; }
        public string BPP_CATEGORY_SEGMENT_LONG_NAME { get; set; }
        public string BPP_CATEGORY_SEGMENT_SHORT_NAME { get; set; }
        public string BPP_SUB_CATEGORY_CODE { get; set; }
        public string BPP_SUB_CATEGORY_LONG_NAME { get; set; }
        public string BPP_SUB_CATEGORY_SHORT_NAME { get; set; }
        public string BPP_CATEGORY_CODE { get; set; }
        public string BPP_CATEGORY_LONG_NAME { get; set; }
        public string BPP_CATEGORY_SHORT_NAME { get; set; }
        public string BPP_CATEGORY_GROUP_CODE { get; set; }
        public string BPP_CATEGORY_GROUP_LONG_NAME { get; set; }
        public string BPP_CATEGORY_GROUP_SHORT_NAME { get; set; }
        public string BPP_MASTER_CATEGORY_CODE { get; set; }
        public string BPP_MASTER_CATEGORY_LONG_NAME { get; set; }
        public string BPP_MASTER_CATEGORY_SHORT_NAME { get; set; }
        public string BPP_SUB_BRAND_CODE { get; set; }
        public string BPP_SUB_BRAND_LONG_NAME { get; set; }
        public string BPP_SUB_BRAND_SHORT_NAME { get; set; }
        public string BPP_BRAND_CODE { get; set; }
        public string BPP_BRAND_LONG_NAME { get; set; }
        public string BPP_BRAND_SHORT_NAME { get; set; }
        public string BPP_BRAND_FAMILY_CODE { get; set; }
        public string BPP_BRAND_FAMILY_LONG_NAME { get; set; }
        public string BPP_BRAND_FAMILY_SHORT_NAME { get; set; }
        public string BPP_MANUFACTURER_CODE { get; set; }
        public string BPP_MANUFACTURER_LONG_NAME { get; set; }
        public string BPP_MANUFACTURER_SHORT_NAME { get; set; }
        public string BPP_FLAVOR_CODE { get; set; }
        public string BPP_FLAVOR_LONG_NAME { get; set; }
        public string BPP_FLAVOR_SHORT_NAME { get; set; }
        public string BPP_FLAVOR_GROUP_CODE { get; set; }
        public string BPP_FLAVOR_GROUP_LONG_NAME { get; set; }
        public string BPP_FLAVOR_GROUP_SHORT_NAME { get; set; }
        public string BPP_CONTAINER_VOLUME_CODE { get; set; }
        public decimal? BPP_CONTAINER_VOLUME { get; set; }
        public string BPP_CONTAINER_VOLUME_UOM { get; set; }
        public string BPP_CONTAINER_VOLUME_UOM_DESC { get; set; }
        public string BPP_CONTAINER_PACK_SEGMENT_CODE { get; set; }
        public string BPP_CONTAINER_PACK_SEGMENT_LONG_NAME { get; set; }
        public string BPP_CONTAINER_PACK_SEGMENT_SHORT_NAME { get; set; }
        public string BPP_CONTAINER_SERVE_SIZE_CODE { get; set; }
        public string BPP_CONTAINER_SERVE_SIZE_LONG_NAME { get; set; }
        public string BPP_CONTAINER_SERVE_SIZE_SHORT_NAME { get; set; }
        public string BPP_CONTAINER_FILL_TYPE_CODE { get; set; }
        public string BPP_CONTAINER_FILL_TYPE_LONG_NAME { get; set; }
        public string BPP_CONTAINER_FILL_TYPE_SHORT_NAME { get; set; }
        public string BPP_CONTAINER_SHAPE_CODE { get; set; }
        public string BPP_CONTAINER_SHAPE_LONG_NAME { get; set; }
        public string BPP_CONTAINER_SHAPE_SHORT_NAME { get; set; }
        public string BPP_CONTAINER_TYPE_CODE { get; set; }
        public string BPP_CONTAINER_TYPE_LONG_NAME { get; set; }
        public string BPP_CONTAINER_TYPE_SHORT_NAME { get; set; }
        public string BPP_CONTAINER_MATERIAL_SUB_TYPE_CODE { get; set; }
        public string BPP_CONTAINER_MATERIAL_SUB_TYPE_LONG_NAME { get; set; }
        public string BPP_CONTAINER_MATERIAL_SUB_TYPE_SHORT_NAME { get; set; }
        public string BPP_CONTAINER_MATERIAL_TYPE_CODE { get; set; }
        public string BPP_CONTAINER_MATERIAL_TYPE_LONG_NAME { get; set; }
        public string BPP_CONTAINER_MATERIAL_TYPE_SHORT_NAME { get; set; }
        public string BPP_SECONDARY_PACKAGE_CODE { get; set; }
        public string BPP_SECONDARY_PACKAGE_LONG_NAME { get; set; }
        public string BPP_SECONDARY_PACKAGE_SHORT_NAME { get; set; }
        public DateTime? DATE_FROM { get; set; }
        public DateTime? DATE_TO { get; set; }
        public string ISSCOM_BRAND_CODE { get; set; }
    }
}