// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class DIM_CUSTOMER
    {
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_LONG_NAME { get; set; }
        public string CUSTOMER_SHORT_NAME { get; set; }
        public string CUS_BU_CODE { get; set; }
        public string CUS_CMG_PREMIUM_FLAG { get; set; }
        public string CUS_CONTACT_PERSON_NAME { get; set; }
        public string CUS_DISTRICT { get; set; }
        public string CUS_ENTITY_CODE { get; set; }
        public string CUS_MARKET_AREA { get; set; }
        public string CUS_NEIGHBOURHOOD { get; set; }
        public string CUS_PRIMARY_ENT_SITE_CODE { get; set; }
        public string CUS_PRIMARY_FLAG { get; set; }
        public string CUS_REGISTRATION_NO { get; set; }
        public string CUS_SECTOR { get; set; }
        public string CUS_SITE { get; set; }
        public string CUS_STATE { get; set; }
        public string CUS_SUB_DISTRICT { get; set; }
        public string CUS_SUPPLYSOURCE_CODE { get; set; }
        public string CUS_TIN_NUMBER { get; set; }
        public string CUS_TOWN_VILLAGE { get; set; }
        public string CUSTOMER_SID { get; set; }
        public string CUSTOMER_TRADE_NAME { get; set; }
        public string PRIMARY_FLAG { get; set; }
        public string CUS_CMG_FLAG { get; set; }
        public string CUS_PARENT_CUSTOMER_CODE { get; set; }
        public string CUS_PARENT_CUSTOMER_LONG_NAME { get; set; }
        public string CUS_PARENT_CUSTOMER_SHORT_NAME { get; set; }
        public string CUS_PARENT_CONTACT_PERSON_NAME { get; set; }
        public string CUS_PARENT_CUSTOMER_TRADE_NAME { get; set; }
        public string CUS_PARENT_REGISTRATION_NO { get; set; }
        public string CUS_GROUP_CODE { get; set; }
        public string CUS_GROUP_LONG_NAME { get; set; }
        public string CUS_GROUP_SHORT_NAME { get; set; }
        public string CUS_CMG_CLASS_CODE { get; set; }
        public string CUS_CMG_CLASS_LONG_NAME { get; set; }
        public string CUS_CMG_CLASS_SHORT_NAME { get; set; }
        public string CUS_CMG_VERTICAL_CODE { get; set; }
        public string CUS_CMG_VERTICAL_LONG_NAME { get; set; }
        public string CUS_CMG_VERTICAL_SHORT_NAME { get; set; }
        public string CUS_POS_TYPE_CODE { get; set; }
        public string CUS_POS_TYPE_LONG_NAME { get; set; }
        public string CUS_POS_TYPE_SHORT_NAME { get; set; }
        public string CUS_CATEGORY_CODE { get; set; }
        public string CUS_CATEGORY_SHORT_NAME { get; set; }
        public string CUS_CATEGORY_LONG_NAME { get; set; }
        public string CUS_OUTLET_VPO_CLASS_CODE { get; set; }
        public string CUS_OUTLET_VPO_CLASS_LONG_NAME { get; set; }
        public string CUS_OUTLET_VPO_CLASS_SHORT_NAME { get; set; }
        public string CUS_TOWN_CLASS_CODE { get; set; }
        public string CUS_TOWN_CLASS_LONG_NAME { get; set; }
        public string CUS_TOWN_CLASS_SHORT_NAME { get; set; }
        public DateTime? DATE_FROM { get; set; }
        public DateTime? DATE_TO { get; set; }
    }
}