// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class dim_customer_test1
    {
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_LONG_NAME { get; set; }
        public string CUSTOMER_SHORT_NAME { get; set; }
        public string CUS_PARENT_CUSTOMER_CODE { get; set; }
        public string CUS_PARENT_CUSTOMER_LONG_NAME { get; set; }
        public string CUS_PARENT_CUSTOMER_SHORT_NAME { get; set; }
        public string CUS_CATEGORY_CODE { get; set; }
        public string CUS_CATEGORY_SHORT_NAME { get; set; }
        public string CUS_CATEGORY_LONG_NAME { get; set; }
        public string CUS_OUTLET_VPO_CLASS_CODE { get; set; }
        public string CUS_OUTLET_VPO_CLASS_LONG_NAME { get; set; }
        public string CUS_OUTLET_VPO_CLASS_SHORT_NAME { get; set; }
        public string CUS_TOWN_CLASS_CODE { get; set; }
        public string CUS_TOWN_CLASS_LONG_NAME { get; set; }
        public string CUS_TOWN_CLASS_SHORT_NAME { get; set; }
        public DateTime? DATE_FROM { get; set; }
        public DateTime? DATE_TO { get; set; }
    }
}