// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class DIM_GEOGRAPHY_TEST1
    {
        public string GEO_REGION_CODE { get; set; }
        public string GEO_REGION_LONG_NAME { get; set; }
        public string GEO_REGION_SHORT_NAME { get; set; }
        public string GEO_COUNTRY_GROUP_CODE { get; set; }
        public string GEO_COUNTRY_GROUP_LONG_NAME { get; set; }
        public string GEO_COUNTRY_GROUP_SHORT_NAME { get; set; }
        public string GEO_COUNTRY_CODE { get; set; }
        public string GEO_COUNTRY_LONG_NAME { get; set; }
        public string GEO_COUNTRY_SHORT_NAME { get; set; }
        public string GEO_ZONE_CODE { get; set; }
        public string GEO_ZONE_LONG_NAME { get; set; }
        public string GEO_ZONE_SHORT_NAME { get; set; }
        public string GEO_SUB_ZONE_CODE { get; set; }
        public string GEO_SUB_ZONE_LONG_NAME { get; set; }
        public string GEO_SUB_ZONE_SHORT_NAME { get; set; }
        public string GEO_DDR_ZONE_CODE { get; set; }
        public string GEO_DDR_ZONE_LONG_NAME { get; set; }
        public string GEO_DDR_ZONE_SHORT_NAME { get; set; }
        public string GEO_STATE_CODE { get; set; }
        public string GEO_STATE_LONG_NAME { get; set; }
        public string GEO_STATE_SHORT_NAME { get; set; }
        public string GEO_DISTRICT_CODE { get; set; }
        public string GEO_DISTRICT_LONG_NAME { get; set; }
        public string GEO_DISTRICT_SHORT_NAME { get; set; }
        public string GEO_POSTAL_REGION_CODE { get; set; }
        public string GEO_POSTAL_REGION_LONG_NAME { get; set; }
        public string GEO_POSTAL_REGION_SHORT_NAME { get; set; }
        public string GEO_POSTAL_DIVISION_CODE { get; set; }
        public string GEO_POSTAL_DIVISION_LONG_NAME { get; set; }
        public string GEO_POSTAL_DIVISION_SHORT_NAME { get; set; }
        public string GEO_POSTAL_PINCODE_CODE { get; set; }
        public string GEO_POSTAL_PINCODE_LONG_NAME { get; set; }
        public string GEO_POSTAL_PINCODE_SHORT_NAME { get; set; }
        public string GEO_SUB_DISTRICT_CODE { get; set; }
        public string GEO_SUB_DISTRICT_LONG_NAME { get; set; }
        public string GEO_SUB_DISTRICT_SHORT_NAME { get; set; }
        public string GEO_SECTOR_CODE { get; set; }
        public string GEO_SECTOR_LONG_NAME { get; set; }
        public string GEO_SECTOR_SHORT_NAME { get; set; }
        public string GEO_TOWN_VILLAGE_CODE { get; set; }
        public string GEO_TOWN_VILLAGE_LONG_NAME { get; set; }
        public string GEO_TOWN_VILLAGE_SHORT_NAME { get; set; }
        public string GEO_NEIGHBOURHOOD_CODE { get; set; }
        public string GEO_NEIGHBOURHOOD_LONG_NAME { get; set; }
        public string GEO_NEIGHBOURHOOD_SHORT_NAME { get; set; }
        public DateTime? DATE_FROM { get; set; }
        public DateTime? DATE_TO { get; set; }
        public int Id_new { get; set; }
    }
}