// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class DIM_SALESORG_TEST
    {
        public string ORG_AREA_SALES_HEAD_CODE { get; set; }
        public string ORG_AREA_SALES_HEAD_LONG_NAME { get; set; }
        public string ORG_AREA_SALES_HEAD_SHORT_NAME { get; set; }
        public string ORG_ENTITY_SALES_HEAD_CODE { get; set; }
        public string ORG_ENTITY_SALES_HEAD_FIRST_NAME { get; set; }
        public string ORG_ENTITY_SALES_HEAD_LAST_NAME { get; set; }
        public string ORG_PRE_SALES_REP_CODE { get; set; }
        public string ORG_PRE_SALES_REP_FIRST_NAME { get; set; }
        public string ORG_PRE_SALES_REP_LAST_NAME { get; set; }
        public string ORG_REGIONAL_SALES_HEAD_CODE { get; set; }
        public string ORG_REGIONAL_SALES_HEAD_FIRST_NAME { get; set; }
        public string ORG_REGIONAL_SALES_HEAD_LAST_NAME { get; set; }
        public string ORG_SALES_MANAGER_CODE { get; set; }
        public string ORG_SALES_MANAGER_FIRST_NAME { get; set; }
        public string ORG_SALES_MANAGER_LAST_NAME { get; set; }
        public string ORG_SALES_TEAM_LEAD_CODE { get; set; }
        public string ORG_SALES_TEAM_LEAD_FIRST_NAME { get; set; }
        public string ORG_SALES_TEAM_LEAD_LAST_NAME { get; set; }
    }
}