// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class FHL_CUS_CATEGORY_test
    {
        public int? CUS_CATEGORY_OID { get; set; }
        public string CUS_CATEGORY_CODE { get; set; }
        public string CUS_CATEGORY_SHORT_NAME { get; set; }
        public string CUS_CATEGORY_LONG_NAME { get; set; }
        public DateTime? DATE_FROM { get; set; }
        public DateTime? DATE_TO { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public string DUMMY_FLAG { get; set; }
        public int? ENTITY_OID { get; set; }
        public string SOURCE_SYSTEM_CODE { get; set; }
        public string USER_ID { get; set; }
        public int? CURRENT_EDIT_LEVEL { get; set; }
        public int? SORT_ORDER { get; set; }
        public DateTime? LAST_UPDATE_TIME { get; set; }
        public string LAST_MODIFIED_BY { get; set; }
    }
}