// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models
{
    public partial class SearchConfigDataResult
    {
        public int ConfigId { get; set; }
        public int SubjectAreaId { get; set; }
        public string SubjectAreaName { get; set; }
        public string AssignedUser { get; set; }
        public string Active { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public string ManualSendResendUrl { get; set; }
    }
}
