// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models
{
    public partial class SP_COUNTRY_LISTResult
    {
        public string ENT_COUNTRY_CODE { get; set; }
        public string ENT_COUNTRY_SHORT_NAME { get; set; }
    }
}
