// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models
{
    public partial class SP_GET_MPP_MASTERSResult
    {
        public string MASTER_DISPLAY_NAME { get; set; }
        public string DIMENSION_TABLE { get; set; }
        public string COLUMN_NAME { get; set; }
        public string COLUMN_DISPLAY_NAME { get; set; }
        public string IS_KEY { get; set; }
    }
}
