// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models
{
    public partial class SP_GET_USERS_DETAILSResult
    {
        public string USER_ID { get; set; }
        public string EMAIL_ID { get; set; }
        public string Name { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public string SUBFUNCTION { get; set; }
        public string ROLE_NAME { get; set; }
    }
}
