// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models
{
    public partial class SP_GET_CONFIG_BATCHResult
    {
        public int? CONFIG_ID { get; set; }
        public int SUBJECTAREA_ID { get; set; }
        public string TIME_LEVEL { get; set; }
        public int? PATTERN { get; set; }
        public string FREQUENCY { get; set; }
        public string REPORTING_PERIOD { get; set; }
        public string ONTIMELEVEL { get; set; }
        public DateTime? UPLOADREMINDERDATE { get; set; }
        public DateTime? ESCALATIONDATE { get; set; }
        public DateTime? LOCKDATE { get; set; }
        public string VERSION { get; set; }
        public DateTime? Created_On { get; set; }
        public string Created_By { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public string SCHEDULED { get; set; }
        public string MANUALFLAG { get; set; }
        public int ID { get; set; }
        public string ONTIMECODE { get; set; }
        public string FORTIMECODE { get; set; }
        public string IS_POPULATED { get; set; }
        public DateTime? PERIOD_FROM { get; set; }
        public DateTime? PERIOD_TO { get; set; }
        public string DATA_COLLECTION { get; set; }
    }
}
