// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models
{
    public partial class SP_GETUPLOADPENDINGResult
    {
        public string SUBFUNCTION_NAME { get; set; }
        public string LOCK_DATE { get; set; }
        public string FILE_NAME { get; set; }
    }
}
