// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models
{
    public partial class SP_GETLOOKUPDATAResult
    {
        public string DATA_TYPE { get; set; }
        public string LOOKUP_CODE { get; set; }
        public string LOOK_DESC { get; set; }
    }
}
