// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Models
{
    public partial class SP_UPLOADEDTEMPLATEResult
    {
        public string SUBFUNCTION_NAME { get; set; }
        public string UPLOADDATE { get; set; }
        public string FILE_NAME { get; set; }
        public string DatA_COLLECTION { get; set; }
        public int? CONFIG_ID { get; set; }
        public string PERIOD_TO { get; set; }
        public string FILE_PATH { get; set; }
        public string DOCUMENT_ID { get; set; }
    }
}
