// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SPG_UOM
    {
        public int UOM_ID { get; set; }
        public string UOM_CODE { get; set; }
        public string UOM_DESC { get; set; }
        public string ACTIVE_FLAG { get; set; }
    }
}