// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace DAL.Models
{
    public partial class SPG_SUBFUNCTION
    {
        public int SUBFUNCTION_ID { get; set; }
        public string COUNTRY_NAME { get; set; }
        [Required(ErrorMessage = "Function Name field is required.")]
        [DisplayName("Function Name")]
        public string FUNCTION_NAME { get; set; }
        [Required(ErrorMessage = "Subfunction Name field is required.")]
        [DisplayName("Subfunction Name")]
        public string SUBFUNCTION_NAME { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}