// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SPG_DOCUMENT
    {
        public int DocumentID { get; set; }
        public string ID { get; set; }
        public DateTime? UPLOADDATE { get; set; }
        public string UPLOADEDBY { get; set; }
        public int? APPROVALSTATUSID { get; set; }
        public int? TEMPLATEID { get; set; }
        public string APPROVERID { get; set; }
        public DateTime? APPROVEDON { get; set; }
        public string COMMENTS { get; set; }
        public string FILE_NAME { get; set; }
        public int? LATEST_FLAG_FOR_DAY { get; set; }
        public string FILE_PATH { get; set; }
        public string APPROVER_NAME { get; set; }
    }
}