// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SPG_SUBJECT_DIMENSION
    {
        public int SUBJECT_DIMENSION_ID { get; set; }
        public int? SUBJECTAREA_ID { get; set; }
        public string MPP_DIMENSION_NAME { get; set; }
        public string DIMENSION_TABLE { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}