// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SPG_TIMELEVEL
    {
        public int ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string TIMELEVELCODE { get; set; }
        public string ACTIVE { get; set; }
    }
}