// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SPG_SENDORRESENDTASK
    {
        public int ID { get; set; }
        public int? ATTEMPTS { get; set; }
        public int? CONFIG_ID { get; set; }
        public int? SENT { get; set; }
        public DateTime? LOCKDATE { get; set; }
        public DateTime? UPLOADREMINDERDATE { get; set; }
        public DateTime? ESCALATIONDATE { get; set; }
        public DateTime? CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public string FORTIMECODE { get; set; }
        public string ONTIMECODE { get; set; }
        public DateTime? PERIOD_FROM { get; set; }
        public DateTime? PERIOD_TO { get; set; }
        public string DATA_COLLECTION { get; set; }
        public string IS_POPULATED { get; set; }
        public string IS_AUTO_MANUAL { get; set; }
    }
}