// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SPG_GETTIMECODE
    {
        public int CONFIG_TIMECODE_ID { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string DATA_TYPE { get; set; }
        public int? CONFIG_ID { get; set; }
        public string DOCUMENT_ID { get; set; }
        public string FORTIMECODE { get; set; }
        public int? TEMPLATE_ID { get; set; }
        public string COLUMN_CODE { get; set; }
    }
}