// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SPG_MPP_MASTER
    {
        public int MPP_MASTER_ID { get; set; }
        public int? ENTITY_TYPE_ID { get; set; }
        public string MPP_DIMENSION_NAME { get; set; }
        public string DIMENSION_TABLE { get; set; }
        public string MASTER_NAME { get; set; }
        public string MASTER_DISPLAY_NAME { get; set; }
        public string COLUMN_NAME { get; set; }
        public string COLUMN_DISPLAY_NAME { get; set; }
        public string IS_KEY { get; set; }
        public string ACTIVE_FLAG { get; set; }
    }
}