// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SPG_CONFIG_STRUCTURE
    {
        public int CONFIGUSER_ID { get; set; }
        public string USER_ID { get; set; }
        public int SUBJECTAREA_ID { get; set; }
        public int CONFIG_ID { get; set; }
        public string FIELD_NAME { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string COLLECTION_TYPE { get; set; }
        public string MASTER_NAME { get; set; }
        public string DIMENSION_TABLE { get; set; }
        public string IS_LOOKUP { get; set; }
        public string LOOKUP_TYPE { get; set; }
        public string DATA_TYPE { get; set; }
        public string DISPLAY_TYPE { get; set; }
        public string IS_FILTER { get; set; }
        public string LEVEL { get; set; }
        public string ETL_NAME { get; set; }
        public string IS_ETL { get; set; }
        public string ISCUSTOMIZED { get; set; }
        public int? SEQUENCE { get; set; }
        public int? COLUMNGROUPID { get; set; }
        public string GROUPCOLUMNNAME { get; set; }
        public string IS_SHOW { get; set; }
        public string UOM { get; set; }
        public string IS_KEY { get; set; }
        public string ISGENERATE_MPP { get; set; }
    }
}