// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SPG_USERS_FUNCTION
    {
        public int USER_FUNCTIONID { get; set; }
        public string USER_ID { get; set; }
        public int? ROLE_ID { get; set; }
        public int? SUB_FUNCTION_ID { get; set; }
        public string ACTIVE_FLAG { get; set; }
    }
}