// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SPG_CONFIG_FILTERS
    {
        public int CONFIG_FILTER_ID { get; set; }
        public int? CONFIG_ID { get; set; }
        public string DIMENSION_TABLE { get; set; }
        public string MASTER_COLUMN { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
        public DateTime? MODIFIED_ON { get; set; }
        public int? MASTER_COLUMN_LEVEL { get; set; }
        public string MASTER_DISPLAY_NAME { get; set; }
    }
}