// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SPG_CONFIGURATION
    {
        public int CONFIG_ID { get; set; }
        public string USER_ID { get; set; }
        public int? SUBJECTAREA_ID { get; set; }
        public string Config_Name { get; set; }
        public string DATA_COLLECTION { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public string SCHEDULED { get; set; }
        public int? PATTERN { get; set; }
        public int? LOCK_DATE { get; set; }
        public int? REMMINDER_DATE { get; set; }
        public int? ESCALATION_DATE { get; set; }
        public int? PATTERN_MONTH { get; set; }
        public DateTime? EFFECTIVE_FROM { get; set; }
        public DateTime? EFFECTIVE_TO { get; set; }
        public string IS_POPULATED { get; set; }
        public string ONLINEDATAENTRY { get; set; }
        public string WHERECLAUSE { get; set; }
        public string APPROVER_ID { get; set; }
        public string APPROVER_EMAILD { get; set; }
        public string APPROVER_NAME { get; set; }
        public string Created_By { get; set; }
        public DateTime? Created_On { get; set; }
        public DateTime? MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}