// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SPG_GET_PERIOD
    {
        public int PERIOD_ID { get; set; }
        public string FREQUENCY { get; set; }
        public string TIME_LEVEL { get; set; }
        public string PERIOD { get; set; }
        public string FREQUENCY_DISPLAY_NAME { get; set; }
        public string TIME_LEVEL_DISPLAY_NAME { get; set; }
    }
}