// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SPG_TIMECODE
    {
        public int TIMECODE_ID { get; set; }
        public string TIMECODE { get; set; }
        public string DESCRIPTION { get; set; }
        public DateTime? FROMDATE { get; set; }
        public DateTime? TODATE { get; set; }
        public int? TIMELEVELID { get; set; }
    }
}