// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SPG_SUBJECT_MASTER
    {
        public int SUBJECT_MASTER_ID { get; set; }
        public string DIMENSION_TABLE { get; set; }
        public string MASTER_NAME { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string FIELD_NAME { get; set; }
        public int? SUBJECTAREA_ID { get; set; }
        public string IS_SHOW { get; set; }
        public string IS_KEY { get; set; }
    }
}