// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SPG_CONFIGDATA
    {
        public DateTime? DATE_FROM { get; set; }
        public int? TEMPLATE_ID { get; set; }
        public string DOCUMENT_ID { get; set; }
        public int? CONFIG_ID { get; set; }
        public int CONFIGDATA_ID { get; set; }
        public string VC0 { get; set; }
        public string VC1 { get; set; }
        public string VC2 { get; set; }
        public string VC3 { get; set; }
        public string VC4 { get; set; }
        public string VC5 { get; set; }
        public string VC6 { get; set; }
        public string VC7 { get; set; }
        public string VC8 { get; set; }
        public string VC9 { get; set; }
        public string VC10 { get; set; }
        public string VC11 { get; set; }
        public string VC12 { get; set; }
        public string VC13 { get; set; }
        public string VC14 { get; set; }
        public string VC15 { get; set; }
        public decimal? N1 { get; set; }
        public decimal? N2 { get; set; }
        public decimal? N3 { get; set; }
        public decimal? N4 { get; set; }
        public decimal? N5 { get; set; }
        public decimal? N6 { get; set; }
        public decimal? N7 { get; set; }
        public decimal? N8 { get; set; }
        public decimal? N9 { get; set; }
        public decimal? N10 { get; set; }
        public decimal? N11 { get; set; }
        public decimal? N12 { get; set; }
        public decimal? N13 { get; set; }
        public decimal? N14 { get; set; }
        public decimal? N15 { get; set; }
        public DateTime? DT1 { get; set; }
        public DateTime? DT2 { get; set; }
        public DateTime? DT3 { get; set; }
        public DateTime? DT4 { get; set; }
        public DateTime? DT5 { get; set; }
        public DateTime? DT6 { get; set; }
        public DateTime? DT7 { get; set; }
        public DateTime? DT8 { get; set; }
        public DateTime? DT9 { get; set; }
        public DateTime? DT10 { get; set; }
        public string VC16 { get; set; }
        public string VC17 { get; set; }
        public string VC18 { get; set; }
        public string VC19 { get; set; }
        public string VC20 { get; set; }
        public string VC21 { get; set; }
        public string VC22 { get; set; }
        public string VC23 { get; set; }
        public string VC24 { get; set; }
        public string VC25 { get; set; }
        public string VC26 { get; set; }
        public string VC27 { get; set; }
        public string VC28 { get; set; }
        public string VC29 { get; set; }
        public string VC30 { get; set; }
        public string VC31 { get; set; }
        public string VC32 { get; set; }
        public string VC33 { get; set; }
        public string VC34 { get; set; }
        public string VC35 { get; set; }
        public string VC36 { get; set; }
        public string VC37 { get; set; }
        public string VC38 { get; set; }
        public string VC39 { get; set; }
        public string VC40 { get; set; }
        public string VC41 { get; set; }
        public string VC42 { get; set; }
        public string VC43 { get; set; }
        public string VC44 { get; set; }
        public string VC45 { get; set; }
        public string VC46 { get; set; }
        public string VC47 { get; set; }
        public string VC48 { get; set; }
        public string VC49 { get; set; }
        public string VC50 { get; set; }
        public int? P1 { get; set; }
        public int? P2 { get; set; }
        public int? P3 { get; set; }
        public int? P4 { get; set; }
        public int? P5 { get; set; }
        public int? STATUS { get; set; }
        public string SOURCE_SYSTEM_NAME { get; set; }
        public DateTime? LAST_UPDATED_TIME_STAMP { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}