// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DAL.Models
{
    public partial class SPG_USERS
    {
        public int ID { get; set; }
        public string USER_ID { get; set; }
        public string Name { get; set; }
        public string PHONE_NO { get; set; }
        public string EMAIL_ID { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public DateTime? CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? LastMODIFIEDDATE { get; set; }
        public string LastMODIFIEDBY { get; set; }
    }
}