// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SPG_ROLE
    {
        public int ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime CREATED_ON { get; set; }
        public int? ROLE_PRIORITY { get; set; }
    }
}