// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SPG_CONFIG_FILTERS_VALUE
    {
        public int CONFIG_FILTER_VAL_ID { get; set; }
        public int? CONFIG_FILTER_ID { get; set; }
        public string FILTER_VALUE { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime? CREATED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
        public DateTime? MODIFIED_ON { get; set; }
        public string FILTER_TEXT { get; set; }
        public string FLAG_CODE { get; set; }
        public string FLAG_NAME { get; set; }
        public string MASTER_NAME { get; set; }
        public int? CONFIG_ID { get; set; }
        public string DIMENSION_TABLE { get; set; }
    }
}