// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SPG_TEMPLATE
    {
        public int TEMPLATE_ID { get; set; }
        public string FILE_NAME { get; set; }
        public string CREATEDBY { get; set; }
        public DateTime? CREATEDON { get; set; }
        public string UPDATEDBY { get; set; }
        public DateTime? UPDATEDON { get; set; }
        public int? CONFIG_ID { get; set; }
        public DateTime? PERIOD_FROM { get; set; }
        public DateTime? PERIOD_TO { get; set; }
        public DateTime? LOCK_DATE { get; set; }
        public DateTime? UPLOAD_REMINDER_DATE { get; set; }
        public DateTime? ESCALATION_DATE { get; set; }
        public int? UPLOAD_REMINDER_SENT { get; set; }
        public int? ESCALATION_REMINDER_SENT { get; set; }
        public string FILE_CODE { get; set; }
        public DateTime? GENERATED_DATE { get; set; }
        public string FORTIMECODE { get; set; }
        public string ONTIMECODE { get; set; }
        public int? LOCK_REMINDER_SENT { get; set; }
        public string FORTIME { get; set; }
        public string ONTIME { get; set; }
        public string DISCARD_FLAG { get; set; }
        public string DISCARD_REASON { get; set; }
    }
}