// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sponge.Models;

public partial class SpgRole
{
    public int RoleId { get; set; }

    public string RoleName { get; set; }

    public string ActiveFlag { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public int? RolePriority { get; set; }

    public string RoleDefinition { get; set; }
}