// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Sponge.Models;

public partial class SPONGE_DEVContext : DbContext
{
    public SPONGE_DEVContext(DbContextOptions<SPONGE_DEVContext> options)
        : base(options)
    {
    }

    public virtual DbSet<SpgRole> SpgRoles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SpgRole>(entity =>
        {
            entity.HasKey(e => e.RoleId);

            entity.ToTable("SPG_ROLE");

            entity.Property(e => e.RoleId).HasColumnName("ROLE_ID");
            entity.Property(e => e.ActiveFlag)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("ACTIVE_FLAG");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn)
                .HasColumnType("date")
                .HasColumnName("CREATED_ON");
            entity.Property(e => e.RoleDefinition)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("ROLE_DEFINITION");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ROLE_NAME");
            entity.Property(e => e.RolePriority).HasColumnName("ROLE_PRIORITY");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}